#pragma once
// Umbrella header for the platform-independent robot logic.

#include "common/MathUtil.h"
#include "common/Types.h"
#include "config/RobotConfig.h"
#include "hal/ICalibrationStore.h"
#include "hal/IGamepad.h"
#include "hal/IPowerSensor.h"
#include "hal/IServoDriver.h"
#include "input/Buttons.h"
#include "input/InputMapper.h"
#include "kinematics/BodyKinematics.h"
#include "kinematics/LegKinematics.h"
#include "motion/Animation.h"
#include "motion/Gait.h"
#include "motion/MotionController.h"
#include "robot/Command.h"
#include "robot/CommandParser.h"
#include "robot/ConfigValidator.h"
#include "robot/Robot.h"
#include "safety/BatteryMonitor.h"
#include "safety/Faults.h"
#include "servo/AngleGuard.h"
#include "servo/ServoBus.h"
#include "telemetry/EventLog.h"
#include "telemetry/JsonWriter.h"
#include "telemetry/TelemetryJson.h"
